name: CI - Cypress tests with mochawesome

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18.18.0 (pin to avoid --loader deprecation issues)
        uses: actions/setup-node@v4
        with:
          node-version: '18.18.0'

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress tests and generate mochawesome report
        run: |
          npm run test:ci

      - name: Fix mochawesome asset paths (make assets paths web-friendly)
        run: |
          # Replace Windows-style backslashes with forward slashes in the generated HTML
          if [ -f cypress/reports/mochawesome.html ]; then
            sed -i 's|\\|/|g' cypress/reports/mochawesome.html || true
          fi

      - name: Upload mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports 
          retention-days: 3
            
